### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 0xdevalias**
Fix require path

### CODE REVIEW

**Comment by bruno-** [comment]
Thanks for checking the plugin, but that would not work. We're actually requiring a file named `safe_deploy_to.rb` (not capistrano-safe_deploy_to.rb) from the `capistrano` directory.

Check it out [here](https://github.com/bruno-/capistrano-safe-deploy-to/tree/master/lib/capistrano).

**Comment by 0xdevalias** [comment]
Fair enough.

When I tried to include it as described in the README it failed, when I changed it to the modification I made it worked _shrugs_

**Comment by bruno-** [comment]
Hey, that's really unusual. Are we sure it didn't work due to something
else? (or it appeared to work?).

I'd be really happy to look into the original problem (plugin not working
when readme instructions are followed) if you have time to provide more
info.

Things like, ruby, rails, capistrano version, `Capfile` and `deploy.rb`
would be useful for debugging.

**Comment by 0xdevalias** [comment]
Kind of been hacking around with lots of stuff so don't know what state the Capfile/deploy.rb were in at the time I hit the error.

At a minimum I can provide environment type details in case it comes up as an issue in future:

```
$ ruby --version
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
$ rails --version
Rails 4.1.0
$ cap --version
Capistrano Version: 3.2.1 (Rake Version: 10.3.1)
```

from Gemfile

```
 # Capistrano 3.x Deployment
  gem 'capistrano' , '~> 3.2.1'
  gem 'capistrano-rails',   '~> 1.1.1', require: false
  gem 'capistrano-bundler', '~> 1.1.2', require: false
  gem 'capistrano-rbenv', '~> 2.0.2', require: false
  gem 'capistrano-rbenv-install', require: false
  gem 'capistrano-knife-solo', '~>0.1.0', require: false
  gem 'capistrano-safe-deploy-to', '~> 1.1' , require: false
  gem 'capistrano-unicorn-nginx', '~> 2.0' , require: false
```

```
$ cap production deploy --dry-run --trace
cap aborted!
LoadError: cannot load such file -- capistrano/safe-deploy-to
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/alias/huginn/Capfile:38:in `<top (required)>'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/rake_module.rb:28:in `load'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:683:in `raw_load_rakefile'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:94:in `block in load_rakefile'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:93:in `load_rakefile'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:77:in `block in run'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:75:in `run'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/capistrano-3.2.1/lib/capistrano/application.rb:15:in `run'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/capistrano-3.2.1/bin/cap:3:in `<top (required)>'
/Users/alias/.rbenv/versions/2.1.1/bin/cap:23:in `load'
/Users/alias/.rbenv/versions/2.1.1/bin/cap:23:in `<main>'

```

**Comment by bruno-** [comment]
Hey,
this line from the log:

```
LoadError: cannot load such file -- capistrano/safe-deploy-to
```

It inidicates file `capistrano/safe-deploy-to.rb` is trying to load (note the hyphens `-` are used instead of underscores `_`). 

Instead, try changing hyphens to underscores, like this.

```
require 'capistrano/safe_deploy_to'
```

Hope it helps!

**Comment by 0xdevalias** [comment]
_nods_ that certainly seems to have been an oversight on my part :)

Not sure if it's something else i've broken, but the error trace changed to this now:

```
$ cap production deploy --dry-run --trace
cap aborted!
Don't know how to build task 'setup'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/task_manager.rb:62:in `[]'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/task.rb:353:in `[]'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/capistrano-3.2.1/lib/capistrano/dsl/task_enhancements.rb:5:in `before'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/capistrano-safe-deploy-to-1.1.0/lib/capistrano/tasks/safe_deploy_to.rake:31:in `<top (required)>'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/capistrano-safe-deploy-to-1.1.0/lib/capistrano/safe_deploy_to.rb:1:in `load'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/capistrano-safe-deploy-to-1.1.0/lib/capistrano/safe_deploy_to.rb:1:in `<top (required)>'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
/Users/alias/huginn/Capfile:38:in `<top (required)>'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/rake_module.rb:28:in `load'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:683:in `raw_load_rakefile'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:94:in `block in load_rakefile'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:93:in `load_rakefile'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:77:in `block in run'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:75:in `run'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/capistrano-3.2.1/lib/capistrano/application.rb:15:in `run'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/capistrano-3.2.1/bin/cap:3:in `<top (required)>'
/Users/alias/.rbenv/versions/2.1.1/bin/cap:23:in `load'
/Users/alias/.rbenv/versions/2.1.1/bin/cap:23:in `<main>'
LoadError: cannot load such file -- capistrano/safe_deploy_to
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/alias/huginn/Capfile:38:in `<top (required)>'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/rake_module.rb:28:in `load'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:683:in `raw_load_rakefile'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:94:in `block in load_rakefile'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:93:in `load_rakefile'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:77:in `block in run'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.1/lib/rake/application.rb:75:in `run'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/capistrano-3.2.1/lib/capistrano/application.rb:15:in `run'
/Users/alias/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/capistrano-3.2.1/bin/cap:3:in `<top (required)>'
/Users/alias/.rbenv/versions/2.1.1/bin/cap:23:in `load'
/Users/alias/.rbenv/versions/2.1.1/bin/cap:23:in `<main>'
```

**Pull request closed without merging**
